import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="p-6">
				<main>
					<h1 className="mb-6 text-5xl font-semibold">Info Site</h1>
					{children}
				</main>
			</body>
		</html>
	);
}
